source 'https://rubygems.org'

gem 'byebug'
gem 'dotenv'
gem 'factory_bot'
gem 'json'
gem 'faker'
gem 'rspec'	
gem 'redis'
gem 'selenium-webdriver'
gem 'sidekiq'
gem 'sidekiq-scheduler'
gem 'sinatra'
gem 'twilio-ruby'
gem 'vcr'
gem 'virtus'
gem 'webmock'